import type { Word, Language, Difficulty } from '@drawspy/shared';

// ─── English Words ────────────────────────────────────────────────────────────
const EN_WORDS: Omit<Word, 'id'>[] = [
  // Animals - easy
  { word: 'cat', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'dog', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'fish', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'bird', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'rabbit', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'horse', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'cow', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'pig', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'duck', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'frog', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'elephant', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'lion', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'tiger', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'bear', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'monkey', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'penguin', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'shark', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'snake', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'turtle', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'wolf', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'zebra', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'giraffe', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'crocodile', category: 'animals', difficulty: 'medium', language: 'en' },
  { word: 'parrot', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'octopus', category: 'animals', difficulty: 'medium', language: 'en' },
  { word: 'butterfly', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'bee', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'ant', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'spider', category: 'animals', difficulty: 'easy', language: 'en' },
  { word: 'owl', category: 'animals', difficulty: 'easy', language: 'en' },
  // Food - easy
  { word: 'pizza', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'burger', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'banana', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'apple', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'cake', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'ice cream', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'hotdog', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'taco', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'sushi', category: 'food', difficulty: 'medium', language: 'en' },
  { word: 'sandwich', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'cookie', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'donut', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'popcorn', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'watermelon', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'strawberry', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'lemon', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'carrot', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'broccoli', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'potato', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'tomato', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'spaghetti', category: 'food', difficulty: 'medium', language: 'en' },
  { word: 'steak', category: 'food', difficulty: 'medium', language: 'en' },
  { word: 'pancake', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'waffle', category: 'food', difficulty: 'easy', language: 'en' },
  { word: 'chocolate', category: 'food', difficulty: 'easy', language: 'en' },
  // Objects - easy/medium
  { word: 'chair', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'table', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'lamp', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'phone', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'book', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'clock', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'umbrella', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'hat', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'glasses', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'key', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'door', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'window', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'bed', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'sofa', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'television', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'computer', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'camera', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'guitar', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'piano', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'balloon', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'bicycle', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'crown', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'ring', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'sword', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'shield', category: 'objects', difficulty: 'easy', language: 'en' },
  { word: 'rocket', category: 'objects', difficulty: 'medium', language: 'en' },
  { word: 'telescope', category: 'objects', difficulty: 'medium', language: 'en' },
  { word: 'microscope', category: 'objects', difficulty: 'medium', language: 'en' },
  { word: 'anchor', category: 'objects', difficulty: 'medium', language: 'en' },
  { word: 'compass', category: 'objects', difficulty: 'medium', language: 'en' },
  // Places - easy/medium
  { word: 'beach', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'mountain', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'forest', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'desert', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'city', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'castle', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'island', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'farm', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'hospital', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'school', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'airport', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'bridge', category: 'places', difficulty: 'easy', language: 'en' },
  { word: 'lighthouse', category: 'places', difficulty: 'medium', language: 'en' },
  { word: 'volcano', category: 'places', difficulty: 'medium', language: 'en' },
  { word: 'space station', category: 'places', difficulty: 'medium', language: 'en' },
  // Jobs - easy/medium
  { word: 'doctor', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'teacher', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'chef', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'firefighter', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'police', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'astronaut', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'pilot', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'nurse', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'farmer', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'scientist', category: 'jobs', difficulty: 'medium', language: 'en' },
  { word: 'magician', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'clown', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'pirate', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'knight', category: 'jobs', difficulty: 'easy', language: 'en' },
  { word: 'ninja', category: 'jobs', difficulty: 'easy', language: 'en' },
  // Sports - easy/medium
  { word: 'football', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'basketball', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'tennis', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'swimming', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'boxing', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'skiing', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'surfing', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'golf', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'baseball', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'volleyball', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'cycling', category: 'sports', difficulty: 'easy', language: 'en' },
  { word: 'archery', category: 'sports', difficulty: 'medium', language: 'en' },
  { word: 'gymnastics', category: 'sports', difficulty: 'medium', language: 'en' },
  { word: 'ice skating', category: 'sports', difficulty: 'medium', language: 'en' },
  { word: 'karate', category: 'sports', difficulty: 'easy', language: 'en' },
  // Nature - easy/medium
  { word: 'sun', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'moon', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'star', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'rainbow', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'cloud', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'lightning', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'snowflake', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'wave', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'tree', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'flower', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'mushroom', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'cactus', category: 'nature', difficulty: 'easy', language: 'en' },
  { word: 'tornado', category: 'nature', difficulty: 'medium', language: 'en' },
  { word: 'waterfall', category: 'nature', difficulty: 'medium', language: 'en' },
  { word: 'glacier', category: 'nature', difficulty: 'hard', language: 'en' },
  // Technology - medium
  { word: 'robot', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'satellite', category: 'technology', difficulty: 'medium', language: 'en' },
  { word: 'drone', category: 'technology', difficulty: 'medium', language: 'en' },
  { word: 'helicopter', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'submarine', category: 'technology', difficulty: 'medium', language: 'en' },
  { word: 'hot air balloon', category: 'technology', difficulty: 'medium', language: 'en' },
  { word: 'spaceship', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'calculator', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'headphones', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'microphone', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'battery', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'magnet', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'circuit', category: 'technology', difficulty: 'hard', language: 'en' },
  { word: 'keyboard', category: 'technology', difficulty: 'easy', language: 'en' },
  { word: 'printer', category: 'technology', difficulty: 'easy', language: 'en' },
  // Entertainment
  { word: 'movie', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'concert', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'game controller', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'magic trick', category: 'entertainment', difficulty: 'medium', language: 'en' },
  { word: 'puppet', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'circus', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'carnival', category: 'entertainment', difficulty: 'medium', language: 'en' },
  { word: 'treasure map', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'haunted house', category: 'entertainment', difficulty: 'easy', language: 'en' },
  { word: 'rollercoaster', category: 'entertainment', difficulty: 'medium', language: 'en' },
];

// ─── Turkish Words ────────────────────────────────────────────────────────────
const TR_WORDS: Omit<Word, 'id'>[] = [
  { word: 'kedi', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'köpek', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'balık', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'kuş', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'tavşan', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'at', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'inek', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'domuz', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'ördek', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'kurbağa', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'fil', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'aslan', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'kaplan', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'ayı', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'maymun', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'penguen', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'köpekbalığı', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'yılan', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'kaplumbağa', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'kurt', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'zebra', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'zürafa', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'timsah', category: 'animals', difficulty: 'medium', language: 'tr' },
  { word: 'papağan', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'ahtapot', category: 'animals', difficulty: 'medium', language: 'tr' },
  { word: 'kelebek', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'arı', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'karınca', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'örümcek', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'baykuş', category: 'animals', difficulty: 'easy', language: 'tr' },
  { word: 'pizza', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'hamburger', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'muz', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'elma', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'pasta', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'dondurma', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'sandviç', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'bisküvi', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'donut', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'patlamış mısır', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'karpuz', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'çilek', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'limon', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'havuç', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'brokoli', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'patates', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'domates', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'çikolata', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'simit', category: 'food', difficulty: 'easy', language: 'tr' },
  { word: 'baklava', category: 'food', difficulty: 'medium', language: 'tr' },
  { word: 'sandalye', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'masa', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'lamba', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'telefon', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'kitap', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'saat', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'şemsiye', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'şapka', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'gözlük', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'anahtar', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'kapı', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'pencere', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'yatak', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'koltuk', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'televizyon', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'balon', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'bisiklet', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'taç', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'yüzük', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'kılıç', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'kalkan', category: 'objects', difficulty: 'easy', language: 'tr' },
  { word: 'roket', category: 'objects', difficulty: 'medium', language: 'tr' },
  { word: 'güneş', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'ay', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'yıldız', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'gökkuşağı', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'bulut', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'şimşek', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'kar tanesi', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'dalga', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'ağaç', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'çiçek', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'mantar', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'kaktüs', category: 'nature', difficulty: 'easy', language: 'tr' },
  { word: 'hortum', category: 'nature', difficulty: 'medium', language: 'tr' },
  { word: 'şelale', category: 'nature', difficulty: 'medium', language: 'tr' },
  { word: 'doktor', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'öğretmen', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'aşçı', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'itfaiyeci', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'polis', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'astronot', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'pilot', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'hemşire', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'çiftçi', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'sihirbaz', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'palyaço', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'korsan', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'şövalye', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'ninja', category: 'jobs', difficulty: 'easy', language: 'tr' },
  { word: 'futbol', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'basketbol', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'tenis', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'yüzme', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'boks', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'kayak', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'sörf', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'golf', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'beyzbol', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'voleybol', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'bisiklet yarışı', category: 'sports', difficulty: 'medium', language: 'tr' },
  { word: 'okçuluk', category: 'sports', difficulty: 'medium', language: 'tr' },
  { word: 'jimnastik', category: 'sports', difficulty: 'medium', language: 'tr' },
  { word: 'buz pateni', category: 'sports', difficulty: 'medium', language: 'tr' },
  { word: 'karate', category: 'sports', difficulty: 'easy', language: 'tr' },
  { word: 'robot', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'uydu', category: 'technology', difficulty: 'medium', language: 'tr' },
  { word: 'drone', category: 'technology', difficulty: 'medium', language: 'tr' },
  { word: 'helikopter', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'denizaltı', category: 'technology', difficulty: 'medium', language: 'tr' },
  { word: 'sıcak hava balonu', category: 'technology', difficulty: 'medium', language: 'tr' },
  { word: 'uzay gemisi', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'kulaklık', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'mikrofon', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'pil', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'mıknatıs', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'klavye', category: 'technology', difficulty: 'easy', language: 'tr' },
  { word: 'sahil', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'dağ', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'orman', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'çöl', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'şehir', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'kale', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'ada', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'çiftlik', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'hastane', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'okul', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'havalimanı', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'köprü', category: 'places', difficulty: 'easy', language: 'tr' },
  { word: 'deniz feneri', category: 'places', difficulty: 'medium', language: 'tr' },
  { word: 'volkan', category: 'places', difficulty: 'medium', language: 'tr' },
];

// ─── French Words ─────────────────────────────────────────────────────────────
const FR_WORDS: Omit<Word, 'id'>[] = [
  { word: 'chat', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'chien', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'poisson', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'oiseau', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'lapin', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'cheval', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'vache', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'canard', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'grenouille', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'éléphant', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'lion', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'tigre', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'ours', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'singe', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'pingouin', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'requin', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'serpent', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'tortue', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'loup', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'zèbre', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'girafe', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'crocodile', category: 'animals', difficulty: 'medium', language: 'fr' },
  { word: 'perroquet', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'pieuvre', category: 'animals', difficulty: 'medium', language: 'fr' },
  { word: 'papillon', category: 'animals', difficulty: 'easy', language: 'fr' },
  { word: 'pizza', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'hamburger', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'banane', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'pomme', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'gâteau', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'glace', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'sandwich', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'chocolat', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'fraise', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'citron', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'carotte', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'tomate', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'baguette', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'croissant', category: 'food', difficulty: 'easy', language: 'fr' },
  { word: 'chaise', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'table', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'lampe', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'téléphone', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'livre', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'horloge', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'parapluie', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'chapeau', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'lunettes', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'clé', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'ballon', category: 'objects', difficulty: 'easy', language: 'fr' },
  { word: 'vélo', category: 'objects', difficulty: 'easy', language: 'fr' },
];

// ─── German Words ─────────────────────────────────────────────────────────────
const DE_WORDS: Omit<Word, 'id'>[] = [
  { word: 'Katze', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Hund', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Fisch', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Vogel', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Hase', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Pferd', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Kuh', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Schwein', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Ente', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Frosch', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Elefant', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Löwe', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Tiger', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Bär', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Affe', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Pinguin', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Hai', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Schlange', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Schildkröte', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Wolf', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Zebra', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Giraffe', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Krokodil', category: 'animals', difficulty: 'medium', language: 'de' },
  { word: 'Papagei', category: 'animals', difficulty: 'easy', language: 'de' },
  { word: 'Tintenfisch', category: 'animals', difficulty: 'medium', language: 'de' },
  { word: 'Pizza', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Hamburger', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Banane', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Apfel', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Kuchen', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Eis', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Sandwich', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Schokolade', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Erdbeere', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Zitrone', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Karotte', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Tomate', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Brezel', category: 'food', difficulty: 'easy', language: 'de' },
  { word: 'Stuhl', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Tisch', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Lampe', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Telefon', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Buch', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Uhr', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Regenschirm', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Hut', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Brille', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Schlüssel', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Ballon', category: 'objects', difficulty: 'easy', language: 'de' },
  { word: 'Fahrrad', category: 'objects', difficulty: 'easy', language: 'de' },
];

// ─── Arabic Words ─────────────────────────────────────────────────────────────
const AR_WORDS: Omit<Word, 'id'>[] = [
  { word: 'قطة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'كلب', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'سمكة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'طائر', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'أرنب', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'حصان', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'بقرة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'ضفدع', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'فيل', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'أسد', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'نمر', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'دب', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'قرد', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'بطريق', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'قرش', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'ثعبان', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'سلحفاة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'ذئب', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'زرافة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'تمساح', category: 'animals', difficulty: 'medium', language: 'ar' },
  { word: 'ببغاء', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'أخطبوط', category: 'animals', difficulty: 'medium', language: 'ar' },
  { word: 'فراشة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'نحلة', category: 'animals', difficulty: 'easy', language: 'ar' },
  { word: 'بيتزا', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'برغر', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'موز', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'تفاحة', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'كعكة', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'آيس كريم', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'شوكولاتة', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'فراولة', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'ليمون', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'جزر', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'طماطم', category: 'food', difficulty: 'easy', language: 'ar' },
  { word: 'كرسي', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'طاولة', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'مصباح', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'هاتف', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'كتاب', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'ساعة', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'مظلة', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'قبعة', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'نظارات', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'مفتاح', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'بالون', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'دراجة', category: 'objects', difficulty: 'easy', language: 'ar' },
  { word: 'شمس', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'قمر', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'نجمة', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'قوس قزح', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'سحابة', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'برق', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'شجرة', category: 'nature', difficulty: 'easy', language: 'ar' },
  { word: 'زهرة', category: 'nature', difficulty: 'easy', language: 'ar' },
];

// ─── Spanish Words ────────────────────────────────────────────────────────────
const ES_WORDS: Omit<Word, 'id'>[] = [
  { word: 'gato', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'perro', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'pez', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'pájaro', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'conejo', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'caballo', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'vaca', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'pato', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'rana', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'elefante', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'león', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'tigre', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'oso', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'mono', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'pingüino', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'tiburón', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'serpiente', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'tortuga', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'lobo', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'jirafa', category: 'animals', difficulty: 'easy', language: 'es' },
  { word: 'pizza', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'hamburguesa', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'plátano', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'manzana', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'pastel', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'helado', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'sándwich', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'galleta', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'rosquilla', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'palomitas', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'sandía', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'fresa', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'limón', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'zanahoria', category: 'food', difficulty: 'easy', language: 'es' },
  { word: 'silla', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'mesa', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'lámpara', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'teléfono', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'libro', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'reloj', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'paraguas', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'sombrero', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'gafas', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'llave', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'globo', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'bicicleta', category: 'objects', difficulty: 'easy', language: 'es' },
  { word: 'sol', category: 'nature', difficulty: 'easy', language: 'es' },
  { word: 'luna', category: 'nature', difficulty: 'easy', language: 'es' },
  { word: 'estrella', category: 'nature', difficulty: 'easy', language: 'es' },
  { word: 'nube', category: 'nature', difficulty: 'easy', language: 'es' },
  { word: 'árbol', category: 'nature', difficulty: 'easy', language: 'es' },
  { word: 'flor', category: 'nature', difficulty: 'easy', language: 'es' },
];

// ─── Word Database ────────────────────────────────────────────────────────────

const ALL_WORDS_RAW: Omit<Word, 'id'>[] = [
  ...EN_WORDS,
  ...TR_WORDS,
  ...FR_WORDS,
  ...DE_WORDS,
  ...ES_WORDS,
  ...AR_WORDS,
];

// Add auto-generated IDs
export const ALL_WORDS: Word[] = ALL_WORDS_RAW.map((w, i) => ({
  ...w,
  id: `w_${i.toString().padStart(4, '0')}`,
}));

export function getWordsByLanguage(language: Language): Word[] {
  return ALL_WORDS.filter((w) => w.language === language);
}

export function getCategories(language: Language): string[] {
  return [...new Set(getWordsByLanguage(language).map((w) => w.category))];
}

export function pickWord(params: {
  language: Language;
  category?: string;
  difficulty?: Difficulty | 'easy+medium' | 'all';
  recentWordIds?: string[];
}): Word | null {
  const { language, category, difficulty, recentWordIds = [] } = params;

  let pool = getWordsByLanguage(language);

  if (category && category !== 'random') {
    pool = pool.filter((w) => w.category === category);
  }

  if (difficulty && difficulty !== 'all') {
    if (difficulty === 'easy+medium') {
      pool = pool.filter((w) => w.difficulty === 'easy' || w.difficulty === 'medium');
    } else {
      pool = pool.filter((w) => w.difficulty === difficulty);
    }
  }

  // Filter out recently used words
  const fresh = pool.filter((w) => !recentWordIds.includes(w.id));
  const candidates = fresh.length > 0 ? fresh : pool; // fallback if all used

  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
